### ISSUE TITLE
Missing config file - erigon.conf

### ISSUE THREAD

**Issue by antbelcastro** [belane/erigon-netdata-plugin#2]
Hi,

The link to https://github.com/netdata/go.d.plugin/blob/master/config/go.d/erigon.conf 404s.
Would it be possible to get a reup?

Thanks

**Comment by belane** [comment]
Yes, the link is https://github.com/belane/erigon-netdata-plugin/blob/dev/config/go.d/erigon.conf
I'll fix in the readme
